name: Generate SBOM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Generate SBOM for JavaScript project
      uses: CycloneDX/cyclonedx-github-action@master
      with:
        output-format: 'json'
        sbom-filename: 'sbom-project.json'

    - name: Build Docker image
      run: |
        docker build -t my-node-app:latest .

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM for Docker image
      run: |
        syft docker:my-node-app:latest -o json > sbom-image.json
